# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171108_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', upload_to='avatar/%Y/%m'),
        ),
    ]
