# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
